apiVersion: apps/v1
kind: Deployment
metadata:
  name: Bhumika_app
  labels:
    app: Bhumika_app
  namespace: default
spec:
  selector:
    matchLabels:
      app: Bhumika_app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: Bhumika_app
    spec:
      containers:
      - name: Bhumika_app
        image: Bhumika_app:0.0.1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: Bhumika_app
