apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhumika-app
  labels:
    app: bhumika-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: bhumika-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bhumika-app
    spec:
      containers:
      - name: bhumika-app
        image: bhumika-app:0.0.2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: bhumika-app
