apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bhumika-app
  namespace: default
spec:
  interval: 1m
  path: "./fluxcd/repositories/bhumika_app/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bhumika-app
